# Generated by Django 3.2.9 on 2021-12-09 14:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restapi.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[restapi.validators.validate_name])),
                ('teacher', models.CharField(choices=[('P', 'PAOLA'), ('G', 'GIADA'), ('K', 'KRESTEN'), ('I', 'IKRAM'), ('C', 'CLAUDIO')], default='P', max_length=2, validators=[restapi.validators.validate_teacher])),
                ('instrument', models.CharField(choices=[('G', 'GUITAR'), ('T', 'TRIANGLE'), ('P', 'PIANO'), ('U', 'UKULELE')], default='G', max_length=2, validators=[restapi.validators.validate_instrument])),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, validators=[restapi.validators.validate_date_time])),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), validators=[restapi.validators.validate_duration])),
                ('cost', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, validators=[restapi.validators.validate_cost])),
            ],
        ),
        migrations.CreateModel(
            name='LessonBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='restapi.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
