# Generated by Django 3.2.9 on 2021-12-14 23:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restapi.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, validators=[restapi.validators.validate_name])),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, validators=[restapi.validators.validate_name])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, validators=[restapi.validators.validate_name])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[restapi.validators.validate_name])),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, validators=[restapi.validators.validate_date_time])),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), validators=[restapi.validators.validate_duration])),
                ('cost', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, validators=[restapi.validators.validate_cost])),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.instrument')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='restapi.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='restapi.student')),
            ],
        ),
    ]
