# Generated by Django 3.2.9 on 2021-12-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='instrument',
            field=models.CharField(choices=[('G', 'GUITAR'), ('T', 'TRIANGLE'), ('P', 'PIANO'), ('U', 'UKULELE')], default='G', max_length=2),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.CharField(choices=[('P', 'PAOLA'), ('G', 'GIADA'), ('K', 'KRESTEN'), ('I', 'IKRAM'), ('C', 'CLAUDIO')], default='P', max_length=2),
        ),
    ]
