# Generated by Django 3.2.9 on 2021-12-15 00:00

from django.db import migrations, models
import restapi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[restapi.validators.validate_cost]),
        ),
    ]
