# Generated by Django 3.2.9 on 2021-12-09 20:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonBook',
            new_name='Booking',
        ),
    ]
