# Generated by Django 3.2.9 on 2021-12-03 22:58

from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20211203_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=50, validators=[restapi.models.validate_name]),
        ),
    ]
