# Generated by Django 3.2.9 on 2021-12-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_lesson_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='students',
        ),
    ]
