# Generated by Django 3.2.9 on 2021-12-03 23:29

import datetime
from django.conf import settings
from django.db import migrations, models
import restapi.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0005_lesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6, validators=[restapi.validators.validate_cost]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, validators=[restapi.validators.validate_date_time]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), validators=[restapi.validators.validate_duration]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='instrument',
            field=models.CharField(choices=[('G', 'GUITAR'), ('T', 'TRIANGLE'), ('P', 'PIANO'), ('U', 'UKULELE')], default='G', max_length=2, validators=[restapi.validators.validate_instrument]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, validators=[restapi.validators.validate_students]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.CharField(choices=[('P', 'PAOLA'), ('G', 'GIADA'), ('K', 'KRESTEN'), ('I', 'IKRAM'), ('C', 'CLAUDIO')], default='P', max_length=2, validators=[restapi.validators.validate_teacher]),
        ),
    ]
