# Generated by Django 3.2.9 on 2021-12-09 23:20

from django.db import migrations, models
import restapi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20211209_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='post_code',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=50, validators=[restapi.validators.validate_name]),
        ),
    ]
