GET http://localhost:8000/api/v1/lessons
Authorization: Token 0ade1a6f46bbb0d8be634a9ef7943d22777f4046
###

GET http://localhost:8000/api/v1/lessons/1
Authorization: Token 8e40f8e69e60d2cc11763f345f584e672099b646
###

POST http://localhost:8000/api/v1/lessons/
Authorization: Token 8e40f8e69e60d2cc11763f345f584e672099b646
Content-Type: application/json

  {
    "name": "Chitarra 4",
    "teacher": "G",
    "instrument": "G",
    "date_time": "2021-12-21T20:54:00Z",
    "duration": "01:00:00",
    "cost": "10.00",
    "students": [1]
  }


###

PUT http://localhost:8000/api/v1/lessons/1/
Content-Type: application/json

{
  "name": "Testazzo",
  "teacher": "C",
  "instrument": "T",
  "students": [
    2
  ],
  "date_time": "2021-12-22T12:47:59Z",
  "duration": "01:30:00",
  "cost": "3.00"
}

###

DELETE http://localhost:8000/api/v1/lessons/2/

################################################# Book

GET http://localhost:8000/api/v1/booking
Authorization: Token 0ade1a6f46bbb0d8be634a9ef7943d22777f4046
###

GET http://localhost:8000/api/v1/booking/1
Authorization: Token 66c83b58bfb99f26a858ddb6189f25c8f16900c5
###

POST http://localhost:8000/api/v1/booking/
Content-Type: application/json
Authorization: Token  66c83b58bfb99f26a858ddb6189f25c8f16900c5

{
  "lesson": 2
}


###

PUT http://localhost:8000/api/v1/booking/1/
Content-Type: application/json

{
  "student": 2,
  "lesson": 3
}



###

DELETE http://localhost:8000/api/v1/booking/3/

################################################# AUTH ENDPOINT 

###
post http://localhost:8000/api/v1/auth/login/
Content-Type: application/json

{
  "username": "s1",
  "password": "Paoletta.85"
}

###
POST http://localhost:8000/api/v1/auth/logout/

###
post http://localhost:8000/api/v1/auth/password/reset/


###
post http://localhost:8000/api/v1/auth/password/reset/confirm/


###
post http://localhost:8000/api/v1/auth/password/change/