
@baseUrl = http://localhost:8000/api/v1
@authToken = {{login.response.body.key}}
@type = application/json

# @name login
POST {{baseUrl}}/auth/login/
Content-Type: {{type}}

{
  "username": "t1",
  "password": "Paoletta.85"
}
###
# @name login
POST {{baseUrl}}/auth/login/
Content-Type: {{type}}

{
  "username": "s1",
  "password": "Paoletta.85"
}

### LESSONS ####

###
GET {{baseUrl}}/lessons
Authorization: Token {{authToken}}


###
GET {{baseUrl}}/lessons/1
Authorization: Token {{authToken}} 


###
POST {{baseUrl}}/lessons/
Authorization: Token {{authToken}} 
Content-Type: {{type}}

{
  "name": "Chitarra asdasd",
  "teacher": {
    "id": 1,
    "name": "Teacher 1",
    "user": 3
  },
  "instrument": {
    "id": 1,
    "name": "Guitar"
  },
  "date_time": "2021-12-21T21:54:00+01:00",
  "duration": "01:00:00",
  "cost": "10.00"
}



###
PUT {{baseUrl}}/lessons/37/
Authorization: Token {{authToken}} 
Content-Type: {{type}}

{
  "id": 37,
  "name": "Chitarra asdasd",
  "teacher": {
    "id": 1,
    "name": "Teacher 1",
    "user": 3
  },
  "instrument": {
    "id": 1,
    "name": "Guitar"
  },
  "date_time": "2021-12-21T21:54:00+01:00",
  "duration": "02:00:00",
  "cost": "10.00"
}


###
DELETE {{baseUrl}}/lessons/10/
Authorization: Token {{authToken}} 

### BOOKINGS ####

###
GET {{baseUrl}}/booking
Authorization: Token {{authToken}} 


###
GET {{baseUrl}}/booking/1
Authorization: Token {{authToken}} 



###
POST {{baseUrl}}/booking/
Content-Type: {{type}}
Authorization: Token {{authToken}} 

{
  "lesson": 2
}


###

PUT {{baseUrl}}/booking/1/
Content-Type: {{type}}

{
  "student": 2,
  "lesson": 3
}



###
DELETE {{baseUrl}}/booking/3/



###
POST {{baseUrl}}/auth/logout/

###
POST {{baseUrl}}/auth/password/reset/


###
POST {{baseUrl}}/auth/password/reset/confirm/


###
POST {{baseUrl}}/auth/password/change/