/api/v1/auth/login/	dj_rest_auth.views.LoginView	rest_login
/api/v1/auth/logout/	dj_rest_auth.views.LogoutView	rest_logout
/api/v1/auth/password/change/	dj_rest_auth.views.PasswordChangeView	rest_password_change
/api/v1/auth/password/reset/	dj_rest_auth.views.PasswordResetView	rest_password_reset
/api/v1/auth/password/reset/confirm/	dj_rest_auth.views.PasswordResetConfirmView	rest_password_reset_confirm
/api/v1/auth/registration	dj_rest_auth.registration.views.RegisterView	rest_register
/api/v1/auth/registrationaccount-confirm-email/<key>/	django.views.generic.base.TemplateView	account_confirm_email
/api/v1/auth/registrationresend-email/	dj_rest_auth.registration.views.ResendEmailVerificationView	rest_resend_email
/api/v1/auth/registrationverify-email/	dj_rest_auth.registration.views.VerifyEmailView	rest_verify_email
/api/v1/auth/user/	dj_rest_auth.views.UserDetailsView	rest_user_details
/api/v1/booking/	restapi.views.BookedView	booking-list
/api/v1/booking/<pk>/	restapi.views.BookedView	booking-detail
/api/v1/lessons/	restapi.views.LessonView	lessons-list
/api/v1/lessons/<pk>/	restapi.views.LessonView	lessons-detail



/docs/	rest_framework.schemas.views.SchemaView	api-docs:docs-index
/docs/schema.js	rest_framework.schemas.views.SchemaView	api-docs:schema-js




/jXTqgeaBVkldfvnr/	django.contrib.admin.sites.index	admin:index
/jXTqgeaBVkldfvnr/<app_label>/	django.contrib.admin.sites.app_index	admin:app_list
/jXTqgeaBVkldfvnr/<url>	django.contrib.admin.sites.catch_all_view
/jXTqgeaBVkldfvnr/account/emailaddress/	django.contrib.admin.options.changelist_view	admin:account_emailaddress_changelist
/jXTqgeaBVkldfvnr/account/emailaddress/<path:object_id>/	django.views.generic.base.RedirectView
/jXTqgeaBVkldfvnr/account/emailaddress/<path:object_id>/change/	django.contrib.admin.options.change_view	admin:account_emailaddress_change
/jXTqgeaBVkldfvnr/account/emailaddress/<path:object_id>/delete/	django.contrib.admin.options.delete_view	admin:account_emailaddress_delete
/jXTqgeaBVkldfvnr/account/emailaddress/<path:object_id>/history/	django.contrib.admin.options.history_view	admin:account_emailaddress_history
/jXTqgeaBVkldfvnr/account/emailaddress/add/	django.contrib.admin.options.add_view	admin:account_emailaddress_add
/jXTqgeaBVkldfvnr/auth/group/	django.contrib.admin.options.changelist_view	admin:auth_group_changelist
/jXTqgeaBVkldfvnr/auth/group/<path:object_id>/	django.views.generic.base.RedirectView
/jXTqgeaBVkldfvnr/auth/group/<path:object_id>/change/	django.contrib.admin.options.change_view	admin:auth_group_change
/jXTqgeaBVkldfvnr/auth/group/<path:object_id>/delete/	django.contrib.admin.options.delete_view	admin:auth_group_delete
/jXTqgeaBVkldfvnr/auth/group/<path:object_id>/history/	django.contrib.admin.options.history_view	admin:auth_group_history
/jXTqgeaBVkldfvnr/auth/group/add/	django.contrib.admin.options.add_view	admin:auth_group_add
/jXTqgeaBVkldfvnr/auth/user/	django.contrib.admin.options.changelist_view	admin:auth_user_changelist
/jXTqgeaBVkldfvnr/auth/user/<id>/password/	django.contrib.auth.admin.user_change_password	admin:auth_user_password_change
/jXTqgeaBVkldfvnr/auth/user/<path:object_id>/	django.views.generic.base.RedirectView
/jXTqgeaBVkldfvnr/auth/user/<path:object_id>/change/	django.contrib.admin.options.change_view	admin:auth_user_change
/jXTqgeaBVkldfvnr/auth/user/<path:object_id>/delete/	django.contrib.admin.options.delete_view	admin:auth_user_delete
/jXTqgeaBVkldfvnr/auth/user/<path:object_id>/history/	django.contrib.admin.options.history_view	admin:auth_user_history
/jXTqgeaBVkldfvnr/auth/user/add/	django.contrib.auth.admin.add_view	admin:auth_user_add
/jXTqgeaBVkldfvnr/authtoken/tokenproxy/	django.contrib.admin.options.changelist_view	admin:authtoken_tokenproxy_changelist
/jXTqgeaBVkldfvnr/authtoken/tokenproxy/<path:object_id>/	django.views.generic.base.RedirectView
/jXTqgeaBVkldfvnr/authtoken/tokenproxy/<path:object_id>/change/	django.contrib.admin.options.change_view	admin:authtoken_tokenproxy_change
/jXTqgeaBVkldfvnr/authtoken/tokenproxy/<path:object_id>/delete/	django.contrib.admin.options.delete_view	admin:authtoken_tokenproxy_delete
/jXTqgeaBVkldfvnr/authtoken/tokenproxy/<path:object_id>/history/	django.contrib.admin.options.history_view	admin:authtoken_tokenproxy_history
/jXTqgeaBVkldfvnr/authtoken/tokenproxy/add/	django.contrib.admin.options.add_view	admin:authtoken_tokenproxy_add
/jXTqgeaBVkldfvnr/autocomplete/	django.contrib.admin.sites.autocomplete_view	admin:autocomplete
/jXTqgeaBVkldfvnr/jsi18n/	django.contrib.admin.sites.i18n_javascript	admin:jsi18n
/jXTqgeaBVkldfvnr/login/	django.contrib.admin.sites.login	admin:login
/jXTqgeaBVkldfvnr/logout/	django.contrib.admin.sites.logout	admin:logout
/jXTqgeaBVkldfvnr/password_change/	django.contrib.admin.sites.password_change	admin:password_change
/jXTqgeaBVkldfvnr/password_change/done/	django.contrib.admin.sites.password_change_done	admin:password_change_done
/jXTqgeaBVkldfvnr/r/<int:content_type_id>/<path:object_id>/	django.contrib.contenttypes.views.shortcut	admin:view_on_site
/jXTqgeaBVkldfvnr/restapi/booking/	django.contrib.admin.options.changelist_view	admin:restapi_booking_changelist
/jXTqgeaBVkldfvnr/restapi/booking/<path:object_id>/	django.views.generic.base.RedirectView
/jXTqgeaBVkldfvnr/restapi/booking/<path:object_id>/change/	django.contrib.admin.options.change_view	admin:restapi_booking_change
/jXTqgeaBVkldfvnr/restapi/booking/<path:object_id>/delete/	django.contrib.admin.options.delete_view	admin:restapi_booking_delete
/jXTqgeaBVkldfvnr/restapi/booking/<path:object_id>/history/	django.contrib.admin.options.history_view	admin:restapi_booking_history
/jXTqgeaBVkldfvnr/restapi/booking/add/	django.contrib.admin.options.add_view	admin:restapi_booking_add
/jXTqgeaBVkldfvnr/restapi/instrument/	django.contrib.admin.options.changelist_view	admin:restapi_instrument_changelist
/jXTqgeaBVkldfvnr/restapi/instrument/<path:object_id>/	django.views.generic.base.RedirectView
/jXTqgeaBVkldfvnr/restapi/instrument/<path:object_id>/change/	django.contrib.admin.options.change_view	admin:restapi_instrument_change
/jXTqgeaBVkldfvnr/restapi/instrument/<path:object_id>/delete/	django.contrib.admin.options.delete_view	admin:restapi_instrument_delete
/jXTqgeaBVkldfvnr/restapi/instrument/<path:object_id>/history/	django.contrib.admin.options.history_view	admin:restapi_instrument_history
/jXTqgeaBVkldfvnr/restapi/instrument/add/	django.contrib.admin.options.add_view	admin:restapi_instrument_add
/jXTqgeaBVkldfvnr/restapi/lesson/	django.contrib.admin.options.changelist_view	admin:restapi_lesson_changelist
/jXTqgeaBVkldfvnr/restapi/lesson/<path:object_id>/	django.views.generic.base.RedirectView
/jXTqgeaBVkldfvnr/restapi/lesson/<path:object_id>/change/	django.contrib.admin.options.change_view	admin:restapi_lesson_change
/jXTqgeaBVkldfvnr/restapi/lesson/<path:object_id>/delete/	django.contrib.admin.options.delete_view	admin:restapi_lesson_delete
/jXTqgeaBVkldfvnr/restapi/lesson/<path:object_id>/history/	django.contrib.admin.options.history_view	admin:restapi_lesson_history
/jXTqgeaBVkldfvnr/restapi/lesson/add/	django.contrib.admin.options.add_view	admin:restapi_lesson_add
/jXTqgeaBVkldfvnr/restapi/student/	django.contrib.admin.options.changelist_view	admin:restapi_student_changelist
/jXTqgeaBVkldfvnr/restapi/student/<path:object_id>/	django.views.generic.base.RedirectView
/jXTqgeaBVkldfvnr/restapi/student/<path:object_id>/change/	django.contrib.admin.options.change_view	admin:restapi_student_change
/jXTqgeaBVkldfvnr/restapi/student/<path:object_id>/delete/	django.contrib.admin.options.delete_view	admin:restapi_student_delete
/jXTqgeaBVkldfvnr/restapi/student/<path:object_id>/history/	django.contrib.admin.options.history_view	admin:restapi_student_history
/jXTqgeaBVkldfvnr/restapi/student/add/	django.contrib.admin.options.add_view	admin:restapi_student_add
/jXTqgeaBVkldfvnr/restapi/teacher/	django.contrib.admin.options.changelist_view	admin:restapi_teacher_changelist
/jXTqgeaBVkldfvnr/restapi/teacher/<path:object_id>/	django.views.generic.base.RedirectView
/jXTqgeaBVkldfvnr/restapi/teacher/<path:object_id>/change/	django.contrib.admin.options.change_view	admin:restapi_teacher_change
/jXTqgeaBVkldfvnr/restapi/teacher/<path:object_id>/delete/	django.contrib.admin.options.delete_view	admin:restapi_teacher_delete
/jXTqgeaBVkldfvnr/restapi/teacher/<path:object_id>/history/	django.contrib.admin.options.history_view	admin:restapi_teacher_history
/jXTqgeaBVkldfvnr/restapi/teacher/add/	django.contrib.admin.options.add_view	admin:restapi_teacher_add
/jXTqgeaBVkldfvnr/sites/site/	django.contrib.admin.options.changelist_view	admin:sites_site_changelist
/jXTqgeaBVkldfvnr/sites/site/<path:object_id>/	django.views.generic.base.RedirectView
/jXTqgeaBVkldfvnr/sites/site/<path:object_id>/change/	django.contrib.admin.options.change_view	admin:sites_site_change
/jXTqgeaBVkldfvnr/sites/site/<path:object_id>/delete/	django.contrib.admin.options.delete_view	admin:sites_site_delete
/jXTqgeaBVkldfvnr/sites/site/<path:object_id>/history/	django.contrib.admin.options.history_view	admin:sites_site_history
/jXTqgeaBVkldfvnr/sites/site/add/	django.contrib.admin.options.add_view	admin:sites_site_add



/schema/	rest_framework.schemas.views.SchemaView
/swagger-docs/	rest_framework_swagger.views.SwaggerSchemaView
